import Data.Bits (complement, shiftL, shiftR, (.&.), (.|.))
import qualified Data.Char as Char
import qualified Data.Map.Strict as Map
import qualified Data.Word as Word

data Signal = VAL !Word.Word16 | VAR !String
  deriving (Show)

data Gate = ID Signal | AND Signal Signal | OR Signal Signal | NOT Signal | RSHIFT Signal Int | LSHIFT Signal Int
  deriving (Show)

data Op = And String Signal | Or String Signal | Op String (Word.Word16 -> Word.Word16)

main :: IO ()
main = do
  let a = wire "a" circuit
  let b = wire "a" (Map.insert "b" (ID (VAL a)) circuit)
  print $ "Part a: " ++ show a
  print $ "Part b: " ++ show b

circuit :: Map.Map String Gate
circuit =
  Map.fromList
    [ ("ai", AND (VAR "af") (VAR "ah")),
      ("ll", NOT (VAR "lk")),
      ("is", RSHIFT (VAR "hz") 1),
      ("gp", NOT (VAR "go")),
      ("dv", OR (VAR "du") (VAR "dt")),
      ("aa", RSHIFT (VAR "x") 5),
      ("ba", OR (VAR "at") (VAR "az")),
      ("es", LSHIFT (VAR "eo") 15),
      ("cu", OR (VAR "ci") (VAR "ct")),
      ("f", RSHIFT (VAR "b") 5),
      ("fo", OR (VAR "fm") (VAR "fn")),
      ("ah", NOT (VAR "ag")),
      ("x", OR (VAR "v") (VAR "w")),
      ("j", AND (VAR "g") (VAR "i")),
      ("ar", LSHIFT (VAR "an") 15),
      ("cy", AND (VAL 1) (VAR "cx")),
      ("jy", AND (VAR "jq") (VAR "jw")),
      ("ix", RSHIFT (VAR "iu") 5),
      ("go", AND (VAR "gl") (VAR "gm")),
      ("bx", NOT (VAR "bw")),
      ("jr", RSHIFT (VAR "jp") 3),
      ("hj", AND (VAR "hg") (VAR "hh")),
      ("by", AND (VAR "bv") (VAR "bx")),
      ("et", OR (VAR "er") (VAR "es")),
      ("ks", OR (VAR "kl") (VAR "kr")),
      ("fm", RSHIFT (VAR "et") 1),
      ("h", AND (VAR "e") (VAR "f")),
      ("ao", LSHIFT (VAR "u") 1),
      ("hx", RSHIFT (VAR "he") 1),
      ("ej", AND (VAR "eg") (VAR "ei")),
      ("bw", AND (VAR "bo") (VAR "bu")),
      ("eg", OR (VAR "dz") (VAR "ef")),
      ("ea", RSHIFT (VAR "dy") 3),
      ("gn", OR (VAR "gl") (VAR "gm")),
      ("du", LSHIFT (VAR "da") 1),
      ("aw", OR (VAR "au") (VAR "av")),
      ("gv", OR (VAR "gj") (VAR "gu")),
      ("fb", OR (VAR "eu") (VAR "fa")),
      ("ln", OR (VAR "lg") (VAR "lm")),
      ("g", OR (VAR "e") (VAR "f")),
      ("dn", NOT (VAR "dm")),
      ("m", NOT (VAR "l")),
      ("as", OR (VAR "aq") (VAR "ar")),
      ("gm", RSHIFT (VAR "gj") 5),
      ("hp", AND (VAR "hm") (VAR "ho")),
      ("gi", LSHIFT (VAR "ge") 15),
      ("ki", RSHIFT (VAR "jp") 1),
      ("hi", OR (VAR "hg") (VAR "hh")),
      ("lw", LSHIFT (VAR "lc") 1),
      ("ko", OR (VAR "km") (VAR "kn")),
      ("fk", LSHIFT (VAR "eq") 1),
      ("an", AND (VAL 1) (VAR "am")),
      ("hc", RSHIFT (VAR "gj") 1),
      ("am", AND (VAR "aj") (VAR "al")),
      ("gw", AND (VAR "gj") (VAR "gu")),
      ("kr", AND (VAR "ko") (VAR "kq")),
      ("hb", OR (VAR "ha") (VAR "gz")),
      ("bz", OR (VAR "bn") (VAR "by")),
      ("jc", OR (VAR "iv") (VAR "jb")),
      ("ad", NOT (VAR "ac")),
      ("bv", OR (VAR "bo") (VAR "bu")),
      ("l", AND (VAR "d") (VAR "j")),
      ("ce", LSHIFT (VAR "bk") 1),
      ("dl", OR (VAR "de") (VAR "dk")),
      ("dw", RSHIFT (VAR "dd") 1),
      ("im", AND (VAR "hz") (VAR "ik")),
      ("je", NOT (VAR "jd")),
      ("fp", RSHIFT (VAR "fo") 2),
      ("hv", LSHIFT (VAR "hb") 1),
      ("lg", RSHIFT (VAR "lf") 2),
      ("gl", RSHIFT (VAR "gj") 3),
      ("kk", OR (VAR "ki") (VAR "kj")),
      ("al", NOT (VAR "ak")),
      ("lf", OR (VAR "ld") (VAR "le")),
      ("ck", RSHIFT (VAR "ci") 3),
      ("cd", AND (VAL 1) (VAR "cc")),
      ("ky", NOT (VAR "kx")),
      ("fw", OR (VAR "fp") (VAR "fv")),
      ("ey", AND (VAR "ev") (VAR "ew")),
      ("dx", LSHIFT (VAR "dt") 15),
      ("ay", NOT (VAR "ax")),
      ("bs", AND (VAR "bp") (VAR "bq")),
      ("ij", NOT (VAR "ii")),
      ("cv", AND (VAR "ci") (VAR "ct")),
      ("ir", OR (VAR "iq") (VAR "ip")),
      ("y", RSHIFT (VAR "x") 2),
      ("fs", OR (VAR "fq") (VAR "fr")),
      ("bq", RSHIFT (VAR "bn") 5),
      ("c", ID (VAL 0)),
      ("b", ID (VAL 14146)),
      ("k", OR (VAR "d") (VAR "j")),
      ("ab", OR (VAR "z") (VAR "aa")),
      ("gg", OR (VAR "gf") (VAR "ge")),
      ("dh", OR (VAR "df") (VAR "dg")),
      ("hk", NOT (VAR "hj")),
      ("dj", NOT (VAR "di")),
      ("fn", LSHIFT (VAR "fj") 15),
      ("ly", RSHIFT (VAR "lf") 1),
      ("p", AND (VAR "b") (VAR "n")),
      ("jx", OR (VAR "jq") (VAR "jw")),
      ("gq", AND (VAR "gn") (VAR "gp")),
      ("aq", RSHIFT (VAR "x") 1),
      ("fa", AND (VAR "ex") (VAR "ez")),
      ("fd", NOT (VAR "fc")),
      ("bk", OR (VAR "bj") (VAR "bi")),
      ("av", RSHIFT (VAR "as") 5),
      ("hy", LSHIFT (VAR "hu") 15),
      ("gt", NOT (VAR "gs")),
      ("fv", AND (VAR "fs") (VAR "fu")),
      ("dk", AND (VAR "dh") (VAR "dj")),
      ("cc", AND (VAR "bz") (VAR "cb")),
      ("er", RSHIFT (VAR "dy") 1),
      ("he", OR (VAR "hc") (VAR "hd")),
      ("ga", OR (VAR "fo") (VAR "fz")),
      ("u", OR (VAR "t") (VAR "s")),
      ("d", RSHIFT (VAR "b") 2),
      ("jz", NOT (VAR "jy")),
      ("ia", RSHIFT (VAR "hz") 2),
      ("kx", AND (VAR "kk") (VAR "kv")),
      ("gd", AND (VAR "ga") (VAR "gc")),
      ("gf", LSHIFT (VAR "fl") 1),
      ("ca", AND (VAR "bn") (VAR "by")),
      ("hs", NOT (VAR "hr")),
      ("bt", NOT (VAR "bs")),
      ("lh", RSHIFT (VAR "lf") 3),
      ("ax", AND (VAR "au") (VAR "av")),
      ("ge", AND (VAL 1) (VAR "gd")),
      ("jt", OR (VAR "jr") (VAR "js")),
      ("fz", AND (VAR "fw") (VAR "fy")),
      ("ja", NOT (VAR "iz")),
      ("t", LSHIFT (VAR "c") 1),
      ("eb", RSHIFT (VAR "dy") 5),
      ("br", OR (VAR "bp") (VAR "bq")),
      ("i", NOT (VAR "h")),
      ("dt", AND (VAL 1) (VAR "ds")),
      ("ae", AND (VAR "ab") (VAR "ad")),
      ("bj", LSHIFT (VAR "ap") 1),
      ("bu", AND (VAR "br") (VAR "bt")),
      ("cb", NOT (VAR "ca")),
      ("em", NOT (VAR "el")),
      ("w", LSHIFT (VAR "s") 15),
      ("gr", OR (VAR "gk") (VAR "gq")),
      ("fi", AND (VAR "ff") (VAR "fh")),
      ("kj", LSHIFT (VAR "kf") 15),
      ("fx", AND (VAR "fp") (VAR "fv")),
      ("lj", OR (VAR "lh") (VAR "li")),
      ("bp", RSHIFT (VAR "bn") 3),
      ("kb", OR (VAR "jp") (VAR "ka")),
      ("lx", OR (VAR "lw") (VAR "lv")),
      ("jb", AND (VAR "iy") (VAR "ja")),
      ("ek", OR (VAR "dy") (VAR "ej")),
      ("bi", AND (VAL 1) (VAR "bh")),
      ("ku", NOT (VAR "kt")),
      ("ap", OR (VAR "ao") (VAR "an")),
      ("ii", AND (VAR "ia") (VAR "ig")),
      ("ez", NOT (VAR "ey")),
      ("cg", RSHIFT (VAR "bn") 1),
      ("fl", OR (VAR "fk") (VAR "fj")),
      ("cf", OR (VAR "ce") (VAR "cd")),
      ("fc", AND (VAR "eu") (VAR "fa")),
      ("kh", OR (VAR "kg") (VAR "kf")),
      ("ju", AND (VAR "jr") (VAR "js")),
      ("iw", RSHIFT (VAR "iu") 3),
      ("di", AND (VAR "df") (VAR "dg")),
      ("do", AND (VAR "dl") (VAR "dn")),
      ("le", LSHIFT (VAR "la") 15),
      ("gh", RSHIFT (VAR "fo") 1),
      ("gx", NOT (VAR "gw")),
      ("gc", NOT (VAR "gb")),
      ("jl", LSHIFT (VAR "ir") 1),
      ("ak", AND (VAR "x") (VAR "ai")),
      ("hh", RSHIFT (VAR "he") 5),
      ("lv", AND (VAL 1) (VAR "lu")),
      ("fu", NOT (VAR "ft")),
      ("gj", OR (VAR "gh") (VAR "gi")),
      ("li", RSHIFT (VAR "lf") 5),
      ("z", RSHIFT (VAR "x") 3),
      ("e", RSHIFT (VAR "b") 3),
      ("hf", RSHIFT (VAR "he") 2),
      ("fy", NOT (VAR "fx")),
      ("jw", AND (VAR "jt") (VAR "jv")),
      ("hz", OR (VAR "hx") (VAR "hy")),
      ("kc", AND (VAR "jp") (VAR "ka")),
      ("fe", AND (VAR "fb") (VAR "fd")),
      ("il", OR (VAR "hz") (VAR "ik")),
      ("db", RSHIFT (VAR "ci") 1),
      ("gb", AND (VAR "fo") (VAR "fz")),
      ("ft", AND (VAR "fq") (VAR "fr")),
      ("gk", RSHIFT (VAR "gj") 2),
      ("ci", OR (VAR "cg") (VAR "ch")),
      ("ch", LSHIFT (VAR "cd") 15),
      ("kg", LSHIFT (VAR "jm") 1),
      ("ik", AND (VAR "ih") (VAR "ij")),
      ("fq", RSHIFT (VAR "fo") 3),
      ("fr", RSHIFT (VAR "fo") 5),
      ("fj", AND (VAL 1) (VAR "fi")),
      ("la", AND (VAL 1) (VAR "kz")),
      ("jh", AND (VAR "iu") (VAR "jf")),
      ("ct", AND (VAR "cq") (VAR "cs")),
      ("ep", LSHIFT (VAR "dv") 1),
      ("hm", OR (VAR "hf") (VAR "hl")),
      ("kp", AND (VAR "km") (VAR "kn")),
      ("dm", AND (VAR "de") (VAR "dk")),
      ("dg", RSHIFT (VAR "dd") 5),
      ("lp", NOT (VAR "lo")),
      ("jv", NOT (VAR "ju")),
      ("fh", NOT (VAR "fg")),
      ("cp", AND (VAR "cm") (VAR "co")),
      ("ed", AND (VAR "ea") (VAR "eb")),
      ("df", RSHIFT (VAR "dd") 3),
      ("gu", AND (VAR "gr") (VAR "gt")),
      ("eq", OR (VAR "ep") (VAR "eo")),
      ("cr", AND (VAR "cj") (VAR "cp")),
      ("lr", OR (VAR "lf") (VAR "lq")),
      ("ha", LSHIFT (VAR "gg") 1),
      ("eu", RSHIFT (VAR "et") 2),
      ("ji", NOT (VAR "jh")),
      ("en", AND (VAR "ek") (VAR "em")),
      ("jo", LSHIFT (VAR "jk") 15),
      ("ih", OR (VAR "ia") (VAR "ig")),
      ("gy", AND (VAR "gv") (VAR "gx")),
      ("fg", AND (VAR "et") (VAR "fe")),
      ("lk", AND (VAR "lh") (VAR "li")),
      ("ip", AND (VAL 1) (VAR "io")),
      ("ke", AND (VAR "kb") (VAR "kd")),
      ("kn", RSHIFT (VAR "kk") 5),
      ("ig", AND (VAR "id") (VAR "if")),
      ("lt", NOT (VAR "ls")),
      ("dy", OR (VAR "dw") (VAR "dx")),
      ("dq", AND (VAR "dd") (VAR "do")),
      ("ls", AND (VAR "lf") (VAR "lq")),
      ("kd", NOT (VAR "kc")),
      ("el", AND (VAR "dy") (VAR "ej")),
      ("kf", AND (VAL 1) (VAR "ke")),
      ("ff", OR (VAR "et") (VAR "fe")),
      ("ic", RSHIFT (VAR "hz") 5),
      ("dp", OR (VAR "dd") (VAR "do")),
      ("cq", OR (VAR "cj") (VAR "cp")),
      ("dr", NOT (VAR "dq")),
      ("ld", RSHIFT (VAR "kk") 1),
      ("jj", AND (VAR "jg") (VAR "ji")),
      ("hq", OR (VAR "he") (VAR "hp")),
      ("hl", AND (VAR "hi") (VAR "hk")),
      ("ds", AND (VAR "dp") (VAR "dr")),
      ("eh", AND (VAR "dz") (VAR "ef")),
      ("ib", RSHIFT (VAR "hz") 3),
      ("dd", OR (VAR "db") (VAR "dc")),
      ("iq", LSHIFT (VAR "hw") 1),
      ("hr", AND (VAR "he") (VAR "hp")),
      ("cs", NOT (VAR "cr")),
      ("lo", AND (VAR "lg") (VAR "lm")),
      ("hw", OR (VAR "hv") (VAR "hu")),
      ("io", AND (VAR "il") (VAR "in")),
      ("ei", NOT (VAR "eh")),
      ("hd", LSHIFT (VAR "gz") 15),
      ("gs", AND (VAR "gk") (VAR "gq")),
      ("eo", AND (VAL 1) (VAR "en")),
      ("kq", NOT (VAR "kp")),
      ("ew", RSHIFT (VAR "et") 5),
      ("lm", AND (VAR "lj") (VAR "ll")),
      ("hg", RSHIFT (VAR "he") 3),
      ("ev", RSHIFT (VAR "et") 3),
      ("bf", AND (VAR "as") (VAR "bd")),
      ("cx", AND (VAR "cu") (VAR "cw")),
      ("ka", AND (VAR "jx") (VAR "jz")),
      ("o", OR (VAR "b") (VAR "n")),
      ("bh", AND (VAR "be") (VAR "bg")),
      ("hu", AND (VAL 1) (VAR "ht")),
      ("gz", AND (VAL 1) (VAR "gy")),
      ("ho", NOT (VAR "hn")),
      ("cm", OR (VAR "ck") (VAR "cl")),
      ("ef", AND (VAR "ec") (VAR "ee")),
      ("lz", LSHIFT (VAR "lv") 15),
      ("kv", AND (VAR "ks") (VAR "ku")),
      ("if", NOT (VAR "ie")),
      ("hn", AND (VAR "hf") (VAR "hl")),
      ("s", AND (VAL 1) (VAR "r")),
      ("ie", AND (VAR "ib") (VAR "ic")),
      ("ht", AND (VAR "hq") (VAR "hs")),
      ("ag", AND (VAR "y") (VAR "ae")),
      ("ee", NOT (VAR "ed")),
      ("bm", LSHIFT (VAR "bi") 15),
      ("dz", RSHIFT (VAR "dy") 2),
      ("cj", RSHIFT (VAR "ci") 2),
      ("bg", NOT (VAR "bf")),
      ("in", NOT (VAR "im")),
      ("ex", OR (VAR "ev") (VAR "ew")),
      ("id", OR (VAR "ib") (VAR "ic")),
      ("bo", RSHIFT (VAR "bn") 2),
      ("de", RSHIFT (VAR "dd") 2),
      ("bn", OR (VAR "bl") (VAR "bm")),
      ("bl", RSHIFT (VAR "as") 1),
      ("ec", OR (VAR "ea") (VAR "eb")),
      ("lq", AND (VAR "ln") (VAR "lp")),
      ("km", RSHIFT (VAR "kk") 3),
      ("iu", OR (VAR "is") (VAR "it")),
      ("iv", RSHIFT (VAR "iu") 2),
      ("be", OR (VAR "as") (VAR "bd")),
      ("it", LSHIFT (VAR "ip") 15),
      ("iy", OR (VAR "iw") (VAR "ix")),
      ("kl", RSHIFT (VAR "kk") 2),
      ("bc", NOT (VAR "bb")),
      ("cl", RSHIFT (VAR "ci") 5),
      ("ma", OR (VAR "ly") (VAR "lz")),
      ("ac", AND (VAR "z") (VAR "aa")),
      ("jn", RSHIFT (VAR "iu") 1),
      ("dc", LSHIFT (VAR "cy") 15),
      ("cz", LSHIFT (VAR "cf") 1),
      ("au", RSHIFT (VAR "as") 3),
      ("da", OR (VAR "cz") (VAR "cy")),
      ("kz", AND (VAR "kw") (VAR "ky")),
      ("a", ID (VAR "lx")),
      ("iz", AND (VAR "iw") (VAR "ix")),
      ("lu", AND (VAR "lr") (VAR "lt")),
      ("js", RSHIFT (VAR "jp") 5),
      ("az", AND (VAR "aw") (VAR "ay")),
      ("jf", AND (VAR "jc") (VAR "je")),
      ("lc", OR (VAR "lb") (VAR "la")),
      ("co", NOT (VAR "cn")),
      ("lb", LSHIFT (VAR "kh") 1),
      ("jk", AND (VAL 1) (VAR "jj")),
      ("af", OR (VAR "y") (VAR "ae")),
      ("cn", AND (VAR "ck") (VAR "cl")),
      ("kw", OR (VAR "kk") (VAR "kv")),
      ("cw", NOT (VAR "cv")),
      ("kt", AND (VAR "kl") (VAR "kr")),
      ("jg", OR (VAR "iu") (VAR "jf")),
      ("bb", AND (VAR "at") (VAR "az")),
      ("jq", RSHIFT (VAR "jp") 2),
      ("jd", AND (VAR "iv") (VAR "jb")),
      ("jp", OR (VAR "jn") (VAR "jo")),
      ("aj", OR (VAR "x") (VAR "ai")),
      ("bd", AND (VAR "ba") (VAR "bc")),
      ("jm", OR (VAR "jl") (VAR "jk")),
      ("v", RSHIFT (VAR "b") 1),
      ("r", AND (VAR "o") (VAR "q")),
      ("q", NOT (VAR "p")),
      ("n", AND (VAR "k") (VAR "m")),
      ("at", RSHIFT (VAR "as") 2)
    ]

eval :: Signal -> [Op] -> Map.Map String Gate -> Word.Word16
eval (VAR s) ops cmap = case Map.lookup s cmap of
  Nothing -> error "Invalid signal"
  Just (ID signal) -> eval signal (Op s id : ops) cmap
  Just (NOT signal) -> eval signal (Op s complement : ops) cmap
  Just (AND signal1 signal2) -> eval signal1 (And s signal2 : ops) cmap
  Just (OR signal1 signal2) -> eval signal1 (Or s signal2 : ops) cmap
  Just (RSHIFT signal n) -> eval signal (Op s (`shiftR` n) : ops) cmap
  Just (LSHIFT signal n) -> eval signal (Op s (`shiftL` n) : ops) cmap
eval (VAL x) ops cmap = exec x ops cmap

exec :: Word.Word16 -> [Op] -> Map.Map String Gate -> Word.Word16
exec x [] cmap = x
exec x ((Op s f) : ops) cmap = let y = f $! x in exec y ops (Map.insert s (ID (VAL y)) cmap)
exec x ((And s signal) : ops) cmap = eval signal (Op s (x .&.) : ops) cmap
exec x ((Or s signal) : ops) cmap = eval signal (Op s (x .|.) : ops) cmap

wire :: String -> Map.Map String Gate -> Word.Word16
wire s = eval (VAR s) []
